import type { NextPage } from "next";
import Head from "next/head";
import { Data } from "../data";
import { Available } from "./components/Available";
import { Contact } from "./components/Contact";
import { Hero } from "./components/Hero";
import { Navbar } from "./components/Navbar";
import { Properties } from "./components/Properties";

const Home: NextPage = () => {
	return (
		<div>
			<Head>
				<title>Real Estate</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
				<link rel="preconnect" href="https://fonts.googleapis.com" />
				<link rel="preconnect" href="https://fonts.gstatic.com" />
				<link
					href="https://fonts.googleapis.com/css2?family=Inconsolata:wght@400;700&display=swap"
					rel="stylesheet"
				/>
			</Head>
			<Navbar />
			<Hero />
			<Properties data={Data} />
			<Available />
			<Contact />
		</div>
	);
};

export default Home;
